# Лабораторная работа 2. Встроенные типы объектов в Pyhon

Четверикова Вера Борисовна, 10.03.2025

# Задание 1. Построение иерархии встроенных типов в Python

## 1. Иерархия встроенных типов

1. **Числовые типы (Numbers)**
   - **int** (целые числа)
     - Пример: `1`, `2`, `-5`
     - Изменяемость: неизменяемый
   - **float** (числа с плавающей точкой)
     - Пример: `1.0`, `3.14`, `-2.5`
     - Изменяемость: неизменяемый
   - **complex** (комплексные числа)
     - Пример: `1 + 2j`, `3 + 4j`
     - Изменяемость: неизменяемый
   - **bool** (логические значения)
     - Пример: `True`, `False`
     - Изменяемость: неизменяемый

2. **Коллекции (Collections)**
   - **Последовательности (Sequences)**
     - **str** (строки)
       - Пример: `'hello'`, `"world"`
       - Упорядоченность: упорядоченная
       - Изменяемость: неизменяемый
     - **list** (списки)
       - Пример: `[1, 2, 3]`, `['a', 'b', 'c']`
       - Упорядоченность: упорядоченная
       - Изменяемость: изменяемый
     - **tuple** (кортежи)
       - Пример: `(1, 2, 3)`, `('a', 'b')`
       - Упорядоченность: упорядоченная
       - Изменяемость: неизменяемый
   - **Отображения (Mappings)**
     - **dict** (словари)
       - Пример: `{'key': 'value', 'name': 'Alice'}`
       - Упорядоченность: неупорядоченная (в Python 3.7+ сохраняет порядок вставки)
       - Изменяемость: изменяемый
   - **Множества (Sets)**
     - **set** (множества)
       - Пример: `{1, 2, 3}`
       - Упорядоченность: неупорядоченная
       - Изменяемость: изменяемый
     - **frozenset** (неизменяемые множества)
       - Пример: `frozenset([1, 2, 3])`
       - Упорядоченность: неупорядоченная
       - Изменяемость: неизменяемый

# Задание 2. Проработка примеров, представленных в лекционном файле

## Задания 2.1, 2.2

### 2. Объект как фундаментальное понятие в Python. Встроенные типы объектов

#### 2.1 Понятие объекта. Атрибуты. Методы. Встроенные типы объектов
Объект в Python — это базовая сущность для представления данных. К объектам в Python относятся: данные встроенных типов, встроенные и пользовательские функции, файлы, модули, встроенные и пользовательские классы, экземпляры классов и т.д. Внутренне объекты представляют собой области выделенной памяти с достаточным пространством для хранения информации об объекте. У объекта могут быть метаданные, которые называются атрибутами.

#### 2.2 Встроенные типы объектов, представляющих числа
Примеры создания целых чисел (int) в различных системах счисления: `1_000_111_111_000`, `0b11`, `0o11`, `0x11`, `int()`.

**Создайте объекты невстроенных числовых типов `decimal` и `fraction`. Приведите примеры вызова операций или методов для созданных объектов.**

In [24]:
from decimal import Decimal
from fractions import Fraction

# Создание объектов
decimal_number = Decimal('3.14')
fraction_number = Fraction(1, 3)

# Примеры операций
print(decimal_number + Decimal('1.86'))  # Сложение
print(fraction_number * Fraction(2, 5))    # Умножение

5.00
2/15


Decimal обеспечивает более точные вычисления с плавающей точкой, а Fraction позволяет работать с дробями.

#### 2.3 Встроенные типы последовательностей: str, list, tuple
Строка (str) — это последовательность символов для хранения и представления текста, которую нельзя изменять после ее создания (read-only, immutable). Список (list) — это последовательность объектов произвольных типов, которую можно изменять после ее создания. Кортежи (tuple) — это последовательность объектов произвольных типов, которую нельзя изменять после ее создания (read-only, immutable).

**Определите строку S из четырех символов: S = 'spam'. Измените строку S на 'slam', используя только нарезание и конкатенацию.**

In [29]:
S = 'spam'
S = S[:1] + 'l' + S[2:]  # Изменение на 'slam'
print(S)

slam


**Можно ли было бы выполнить ту же самую операцию с применением только индексации и конкатенации?**

Нет, поскольку строки в Python неизменяемы и нельзя присваивать значения по индексу.

**Примеры для списка и кортежа**

In [35]:
# Список
lst = [1, 2, 3, 4]
lst[1] = 5  # Изменение элемента по индексу
print(lst)

# Кортеж
tpl = (1, 2, 3, 4)

[1, 5, 3, 4]


Строки неизменяемы, что ограничивает возможности их изменения по индексу. Списки, напротив, допускают изменения.

#### 2.4 Встроенный тип отображения: dict
Отображение — это неупорядоченная коллекция элементов в виде пары объектов ключ: значение. Словарь (dict) — это единственный встроенный тип Python, который относится к отображениям.

**Напишите структуру данных, которая представляет вашу персональную информацию.**

In [39]:
personal_info = {
    'name': ('Вера', 'Борисовна', 'Четверикова'),
    'age': 18,
    'workplace': '-',
    'address': '-',
    'email': 'chetverikovvera@gmail.com',
    'phone': '+375(29)688-44-17'
}

print(personal_info['name'])
print(personal_info['age'])

('Вера', 'Борисовна', 'Четверикова')
18


Структуры данных позволяют удобно организовывать и извлекать информацию. Словарь является удобным способом для хранения и доступа к данным.

#### 2.5 Встроенный тип множества: set
Множество (set) — это неупорядоченная коллекция не повторяющихся объектов. Элемент встречается во множестве только однажды независимо от того, сколько раз он добавлялся.

**Приведите пример удаления повторяющихся символов строки с использованием множества.**

In [64]:
string = "happiness can be found"
unique = set(string)  # Удаление повторяющихся символов
print(unique)

{'s', 'a', 'b', 'u', 'i', 'c', 'p', 'e', 'f', ' ', 'o', 'n', 'd', 'h'}


Множества автоматически удаляют дубликаты, что удобно для обработки строк.

#### 2.6 Встроенный булевый тип
Булевый тип в Python имеет только два значения: `True` и `False`. Эти значения используются для логических операций и условных выражений.

#### 2.7 Изменяемые и неизменяемые встроенные типы объектов
Все типы данных в Python делятся на изменяемые (например, списки, словари, множества) и неизменяемые (например, числа, строки, кортежи).
Изменяемые типы позволяют изменять свои значения, в то время как неизменяемые типы не могут быть изменены после создания.

#### 2.8 Интерфейс объекта: операции и методы
Множество операций и методов для конкретного типа объектов называется интерфейсом объекта. 
Операции в Python могут быть представлены с помощью специальных символов или встроенных функций.

**Приведите примеры вызова методов count и index для всех возможных типов объектов.**

In [74]:
# Примеры для строки
str = "happiness"
print(str.count('p'))  # Количество 'p'
print(str.index('i'))  # Индекс 'i'

# Примеры для списка
lst1 = [3, 2, 3, 5, 3]
print(lst1.count(3))  # Количество 3
print(lst1.index(5))  # Индекс 5

2
4
3
3


Методы count и index позволяют удобно работать с элементами объектов, возвращая количество и индекс.

**Пример выражения, в котором для заданной строки последовательно применены три различных строковых метода.**

In [72]:
st = "  Happiness Can Be Found  "
result = st.strip().lower().replace('happiness', 'in deserts')
print(result)

in deserts can be found


***Спецификация:***
- strip(): удаляет пробелы в начале и конце строки.
- lower(): переводит строку в нижний регистр.
- replace(): заменяет подстроку.

**Примеры добавления элемента в список с использованием трех различных списковых методов.**

In [76]:
lst2 = [1, 2, 3]

lst2.append(4)
lst2.insert(0, 0)
lst2.extend([5, 6])

print(lst2)

[0, 1, 2, 3, 4, 5, 6]


**Пример сортировки списка с использованием метода sort и заданного аргумента key.**

In [81]:
lst3 = ['potato', 'cauliflower', 'cucumber']
lst3.sort(key=len)  # Сортировка по длине строки
print(lst3)

['potato', 'cucumber', 'cauliflower']


Сортировка с ключом позволяет изменять порядок элементов по заданному критерию.

**Создайте словарь из 100 элементов с одинаковыми значениями.**

In [95]:
dict1 = {i: 'value' for i in range(100)}
print("Словарь:", dict1)

Словарь: {0: 'value', 1: 'value', 2: 'value', 3: 'value', 4: 'value', 5: 'value', 6: 'value', 7: 'value', 8: 'value', 9: 'value', 10: 'value', 11: 'value', 12: 'value', 13: 'value', 14: 'value', 15: 'value', 16: 'value', 17: 'value', 18: 'value', 19: 'value', 20: 'value', 21: 'value', 22: 'value', 23: 'value', 24: 'value', 25: 'value', 26: 'value', 27: 'value', 28: 'value', 29: 'value', 30: 'value', 31: 'value', 32: 'value', 33: 'value', 34: 'value', 35: 'value', 36: 'value', 37: 'value', 38: 'value', 39: 'value', 40: 'value', 41: 'value', 42: 'value', 43: 'value', 44: 'value', 45: 'value', 46: 'value', 47: 'value', 48: 'value', 49: 'value', 50: 'value', 51: 'value', 52: 'value', 53: 'value', 54: 'value', 55: 'value', 56: 'value', 57: 'value', 58: 'value', 59: 'value', 60: 'value', 61: 'value', 62: 'value', 63: 'value', 64: 'value', 65: 'value', 66: 'value', 67: 'value', 68: 'value', 69: 'value', 70: 'value', 71: 'value', 72: 'value', 73: 'value', 74: 'value', 75: 'value', 76: 'value',

#### 2.9 Переменная
Переменная создается при первом присваивании ей значения. 
Переменная в Python является ссылкой на объект, который хранится в памяти.

**Примеры создания циклического объекта для различных встроенных типов.**

In [100]:
cyclic_l = []
cyclic_l.append(cyclic_l)
print("Циклический объект списка:", cyclic_l)

cyclic_d = {}
cyclic_d["self"] = cyclic_d 
print("Циклический объект словаря:", cyclic_d)

Циклический объект списка: [[...]]
Циклический объект словаря: {'self': {...}}


Циклические ссылки могут создавать сложные структуры данных, полезные для некоторых задач.

**Создайте объект, на который ссылаются четыре переменные. Как можно узнать количество ссылок для заданного объекта?**

In [103]:
a2 = [1, 2, 3]
b1 = a2
c1 = a2
d1 = a2

import sys
print("Количество ссылок на объект a2:", sys.getrefcount(a2))

Количество ссылок на объект a2: 5


Использование sys.getrefcount позволяет отслеживать количество ссылок на объект в памяти.

**Приведите три различных способа копирования списка.**

In [107]:
list3 = [1, 2, 3]

# Способ 1: Используя метод copy
copy1 = list3.copy()

# Способ 2: С помощью среза
copy2 = list3[:]

# Способ 3: С помощью функции list()
copy3 = list(list3)

print("Копии списка:", copy1, copy2, copy3)

Копии списка: [1, 2, 3] [1, 2, 3] [1, 2, 3]


Различные методы копирования помогают избежать изменения оригинального списка при модификации копий.

#### 2.10 Выражение спискового включения
Списковое включение позволяет создавать новый список, применяя выражение к каждому элементу последовательности. 
Синтаксис: `[expr(elem) for elem in sequence]`.

**Приведите пример создания множества с использованием синтаксиса включения с условием.**

In [111]:
unique1 = {char for char in "happiness can be found" if char in "aeiou"}  # Уникальные гласные
print("Уникальные гласные:", unique1)

Уникальные гласные: {'a', 'u', 'i', 'e', 'o'}


Включение с условием позволяет эффективно создавать множества с уникальными значениями.

**Приведите пример создания числовой матрицы размера 7 × 8 на основе списка с использованием вложенных включений.**

In [124]:
matrix1 = [[j for j in range(8)] for i in range(7)]
print("Числовая матрица 7x8:", matrix1)

Числовая матрица 7x8: [[0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7]]


Вложенные списковые включения позволяют создавать сложные структуры данных, такие как матрицы.

**Попробуйте создать аналогичную матрицу, используя инструменты расширения numpy.**

In [118]:
import numpy as np

matrix2 = np.zeros((7, 8))  # Создаем матрицу 7x8, заполненную нулями
print("Числовая матрица 7x8 с использованием numpy:\n", matrix2)

Числовая матрица 7x8 с использованием numpy:
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


Использование библиотеки numpy для работы с матрицами обеспечивает более высокую производительность и удобство.

**Приведите пример создания словаря с использованием синтаксиса включения с двумя уровнями вложенности.**

In [127]:
dict4 = {i: {j: j**2 for j in range(3)} for i in range(5)}
print("Вложенный словарь:", dict4)

Вложенный словарь: {0: {0: 0, 1: 1, 2: 4}, 1: {0: 0, 1: 1, 2: 4}, 2: {0: 0, 1: 1, 2: 4}, 3: {0: 0, 1: 1, 2: 4}, 4: {0: 0, 1: 1, 2: 4}}


Вложенные словари позволяют организовывать данные и структурировать информацию более удобно.

#### 2.11 Форматированный вывод строк
- Существует три способа форматирования строк в Python:
  1. Бинарная операция `%`: `'...%s...%d...' % (obj1, obj2)`.
  2. Метод `format()`: `'...{}...{}...'.format(obj1, obj2)`.
  3. Форматированный строковый литерал (f-строки): `f'...{x}...{y}...'`.

**Приведите пример форматированного вывода с использованием синтаксиса f'...{variable=:...}', где variable – заданная переменная.**

In [142]:
variable1 = 2
print(f'variable1 = {variable1 = :}')

variable1 = variable1 = 2


Форматированный вывод с помощью f-строк обеспечивает более читаемое представление данных.

**Получите аналогичный результат с использованием бинарной операции % и строкового метода format.**

In [149]:
print('variable1 = %s' % variable1) # Используем бинарную операцию
print('variable1 = {}'.format(variable1))  # Используем метод format

variable1 = 2
variable1 = 2


Альтернативные методы форматирования также полезны и позволяют использовать различные подходы к выводам данных.

**Приведите пример форматированного вывода с использованием синтаксиса f'...{expression=:...}', где expression – заданное выражение.**

In [154]:
expression1 = 3.14159 * 2
print(f'Результат выражения: {expression1 = :}')

Результат выражения: expression1 = 6.28318


Этот метод позволяет удобно выводить результаты вычислений с их представлением.

**Получите аналогичный результат с использованием бинарной операции % и строкового метода format.**

In [157]:
print('Результат выражения: %s' % expression1)  # Используем бинарную операцию
print('Результат выражения: {}'.format(expression1))  # Используем метод format

Результат выражения: 6.28318
Результат выражения: 6.28318


Форматирование с использованием различных методов демонстрирует гибкость Python в работе с текстом.

#### 2.12 Файловый объект
Файловый объект создается с помощью функции `open(file, mode)`, где `file` — имя файла, а `mode` — режим обработки.
Режимы обработки могут быть: `'r'` для чтения, `'w'` для записи, `'a'` для добавления и др.

**Приведите пример, в котором используются следующие функции и методы для работы с файловым объектом: open, close, read, readline, readlines, write, writelines.**

In [161]:
# Запись в файл
with open('example.txt', 'w') as f:
    f.write("Happiness can be found\n")  # Записываем строку
    f.writelines(["Line 1\n", "Line 2\n", "Line 3\n"])  # Записываем несколько строк

# Чтение из файла
with open('example.txt', 'r') as f:
    content = f.read()  # Читаем все содержимое
    print("Содержимое файла:\n", content)
    
    f.seek(0)  # Вернуться в начало файла
    first_ln = f.readline()  # Читаем первую строку
    print("Первая строка:", first_ln.strip())

    f.seek(0)  # Вернуться в начало файла
    all_lns = f.readlines()  # Читаем все строки
    print("Все строки:", all_lns)

Содержимое файла:
 Happiness can be found
Line 1
Line 2
Line 3

Первая строка: Happiness can be found
Все строки: ['Happiness can be found\n', 'Line 1\n', 'Line 2\n', 'Line 3\n']


Работа с файловыми объектами включает запись и чтение данных, что является важной частью обработки информации в Python.

## Задание 2.3 

### Фрагмент 1

`print('\c \xc6')`

Ошибка возникает из-за \c, которая не является правильной escape-последовательностью. Python не знает, что с ней делать, поэтому выдает предупреждение. 

### Фрагмент 2

`str1[10]`

Ошибка IndexError возникает, потому что индекс 10 выходит за пределы длины строки str1. В Python индексы начинаются с 0, и если строка короче 11 символов, этот индекс недоступен.

### Фрагмент 3

`[1] + '1'`

Ошибка TypeError возникает, потому что в Python нельзя объединять список и строку напрямую.

### Фрагмент 4

`dict1['two']`

Ошибка KeyError возникает, потому что ключ 'two' отсутствует в словаре dict1.

### Фрагмент 5

`t = [1,2], {1:2}, {1,2}; t[0] = 0`

Ошибка TypeError возникает, потому что t является кортежем, а кортежи в Python неизменяемы.

### Фрагмент 6

`{1, 'str', (1,)}.add([1])`

Ошибка TypeError возникает, потому что нельзя добавлять список [1] в множество.

### Фрагмент 7

`print(dict1.get('one'), dict1.get('three'))`

`dict1['three']`

Ошибка KeyError возникает, потому что вы пытаетесь получить значение по ключу 'three', который отсутствует в словаре dict1. Метод .get() возвращает None, если ключ не найден, но доступ к несуществующему ключу с помощью dict1['three'] вызывает ошибку.

### Фрагмент 8

`print(s, s.find('-'))`

`s.index('-')`

Ошибка ValueError возникает, потому что метод index() не находит подстроку '-' в строке s.

### Фрагмент 9

`a = 1  # создание переменной`

`a, d`

Ошибка NameError возникает, потому что переменная d не определена.

### Фрагмент 10

`print(abs(-1))`

`abs = 5`

`print(abs(-1))`

Ошибка TypeError возникает, потому что после присвоения abs = 5, abs больше не ссылается на функцию abs(), а становится целым числом.

# Задание 3. Ответы на контрольные вопросы из книги М. Лутца

## 1. Глава 4, вопрос 6: Что такое "полиморфизм" и почему о нем нужно заботиться?

Полиморфизм означает, что смысл операции (например, +) зависит от объектов, к которым она применяется. Это позволяет использовать один и тот же оператор для различных типов данных, что делает код более гибким и универсальным. 

*Примеры:*
1. Сложение чисел

In [198]:
a3 = 1
b3 = 99
result = a3 + b3
print(result)

100


2. Сложение строк

In [201]:
str5 = "Wit beyond measure "
str6 = "is a man’s greatest treasure."
result = str5 + str6
print(result)

Wit beyond measure is a man’s greatest treasure.


3. Сложение списков

In [204]:
list01 = [1, 2, 3]
list02 = [4, 5, 6]
result01 = list01 + list02
print(result01)

[1, 2, 3, 4, 5, 6]


## 2. Глава 5, вопрос 7: Как можно преобразовывать целое число в число с плавающей точкой?

Для преобразования целого числа в число с плавающей точкой в Python можно использовать функцию float(). Также смешивание целых чисел и чисел с плавающей точкой в выражениях приводит к автоматическому преобразованию целых чисел в числа с плавающей точкой. Кроме того, операция деления (/) в Python 3 всегда возвращает число с плавающей точкой, даже если оба операнда являются целыми.

*Примеры:*
1. Использование функции float()

In [214]:
integer_val01 = 8
float_val01 = float(integer_val01)
print(float_val01)

8.0


2. Смешивание типов в выражении

In [217]:
a4 = 8
b4 = 2.99
result04 = a4 + b4
print(result04)

10.99


3. Операция деления

In [220]:
x9 = 1000
y9 = 7
result = x9 / y9
print(result)

142.85714285714286


Применение float() и автоматическое преобразование типов делает Python гибким в работе с числовыми данными, что упрощает математические вычисления и работу с различными типами данных.

## 3. Глава 6, вопрос 2: Изменяют ли три оператора значение, выводимое для A?

In [228]:
A = ["spam"]
B = A
B[0] = "shrubbery"

Да, теперь для A выводится ["shrubbery"]. A и B ссылаются на один и тот же список.
Когда мы изменяем первый элемент списка через B, это изменение также видно в A, потому что обе переменные указывают на один и тот же объект.

*Пример:*

In [242]:
print(B)
print(A)

['shrubbery']
['shrubbery']


Изменение происходит не в самих переменных, а в списке, на который они ссылаются. Поэтому, когда мы изменяем его через B, это видно и в A.

## 4. Глава 7, вопрос 6: Сколько символов в строке "a\nb\x0f\000d"?

В строке "a\nb\x0f\000d" содержится 6 символов: a, \n (символ новой строки), b, \x0f, \000, d.

*Пример:*

In [252]:
string01 = "a\nb\x0f\000d"

length01 = len(string01)
print("Длина строки:", length01)

for char in string01:
    print(f"Символ: {char}, Код: {ord(char)}")

Длина строки: 6
Символ: a, Код: 97
Символ: 
, Код: 10
Символ: b, Код: 98
Символ: , Код: 15
Символ: , Код: 0
Символ: d, Код: 100


Используя функцию len(), мы можем подтвердить, что в строке 6 символов. Функция ord() показывает значения кодов для каждого символа, что позволяет увидеть, как интерпретируются управляющие последовательности.

## 5. Глава 8, вопрос 3: Назовите четыре операции, которые изменяют списковый объект на месте в Python.

1. append() — добавляет элемент в конец списка:

In [270]:
list08 = [1, 2, 3]
list08.append(9)
print(list08)

[1, 2, 3, 9]


2. extend() — добавляет элементы из другого списка в конец текущего списка:

In [272]:
list08.extend([6, 5])
print(list08)

[1, 2, 3, 9, 6, 5]


3. sort() — сортирует элементы списка на месте:

In [274]:
list08.sort()
print(list08)

[1, 2, 3, 5, 6, 9]


4. reverse() — разворачивает список на месте:

In [277]:
list08.reverse()
print(list08)

[9, 6, 5, 3, 2, 1]


Эти методы изменяют сам объект списка, а не создают новый.

## 6. Глава 9, вопрос 6: Когда в Python объект считается истинным?

Объект в Python считается истинным, если он соответствует следующим условиям:
- Не нулевое число: Любое число, кроме 0 (например, 1, -1, 3.14), является истинным.
- Непустая коллекция: Это могут быть непустые списки, кортежи, множества, строки или словари (например, [1, 2], 'hello', {1: 'a'}).
- Встроенные значения: Значения True и False также являются истинными и ложными соответственно, где True эквивалентно 1, а False эквивалентно 0.
  
*Примеры:*

In [283]:
# Истинные объекты
print(bool(1))
print(bool(-1))
print(bool(3.14))
print(bool("hello"))
print(bool([1, 2]))
print(bool({'a': 1}))

# Ложные объекты
print(bool(0))
print(bool(0.0))  
print(bool(""))   
print(bool([]))   
print(bool({})) 
print(bool(None)) 

True
True
True
True
True
True
False
False
False
False
False
False


Понимание истинности и ложности объектов в Python позволяет более эффективно управлять логическими операциями и условиями в коде.